### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ghost** [Tanzin01/DriveCompanion#3]
How do I use the app? Copy pasting file path and clicking on either `Start` or `Fix` button doesn't work, and doesn't show any indication that the button has been clicked.

**Comment by Tanzin01** [comment]
Sorry for late reply. Was offline from github

How to use-
1.Copy paste your iso/img full file path(i.e /storage/emulated/0/MyImage.iso considering your .iso file is in phone's "Internal storage")
2. Click run as cdrom
3.Connect your phone with pc via usb cable & do your stuff.
[*Dont touch start button]
4. After done using, you may click fix button. It revert all changes made to your device

**Comment by ghost** [comment]
:+1: That works!

If that doesn't work, try changing the Permanent and Automatic USB Mode in DriveDroid itself to MTP instead of Mass Storage. Running DriveDroid should mostly work with/without DriveCompanion, depending on your device.

**Comment by Tanzin01** [comment]
Yeah, in most cases drivedroid  alone is enough. Except in few cases where it might crash or device wont appear in boot menu(my case atleast).

This is part of the reason behind making the app. Initially i was planning on porting a old linux program(to supports all devices regardless of kernel) but it seemed  much work+due to other reasons, things are at halt now
